[versions]
kotlin = "1.7.20"
kotest = "5.5.4"

[libraries]
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-property = { module = "io.kotest:kotest-property", version.ref = "kotest" }
junit4 = { module = "junit:junit", version = "4.13.2" }

[bundles]
kotest = ["kotest-runner-junit5", "kotest-property", "kotest-assertions"]

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }